<?php
session_start();
require('code128.php');
include ('include/function.php');

 $id1=$_SESSION['name'];
  
$request_id = base64_decode($_GET['id']);
  
		 $srj="select barcode from purchase_request_master where req_id = '$request_id' ";
		  $run9=mysqli_query($conn,$srj);
          while(($row = mysqli_fetch_array($run9)) != false) 
			{
				 $barcode3=$row['barcode'];
				
			}
		
		$raw= "select * from purchase_request_master a , supplier_setup b , portal_user c ,school_branches d 
where a.req_id = '$request_id' and b.supplier_id = a.req_from and a.user_id = c.user_id and d.branch_id = a.branch_id ";
            $smack=mysqli_query($conn,$raw);
             while(($r = mysqli_fetch_array($smack)) != false) 
			{
       $req_date = $r['REQ_DATE'];
	   $remarks = $r['REMARKS'];
	   $request_from = $r['NAME'];
	   $branch_name = $r['branch_name'];
			}


		 
class PDF extends FPDF
{


// Simple table
function data($data)
{
   
    foreach($data as $row)
    {
        foreach($row as $col)
            $this->MultiCell(180,6,$col,0);
            $this->Cell(1,1,'',0,1);
    }
}
	function footer()
{
      $this->SetY(-15);
		$this->SetFont('Arial','B','10');
		$this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
	  
		
	}
}


$pdf = new PDF('P','cm','A4');
$pdf = new PDF_Code128();		


$pdf->SetTopMargin(25);
$pdf->AddPage('L');
$pdf->AliasNbPages();
 $pdf->SetFont('Arial','',12);

$pic = 'school.jpg';
    



      $pdf->Cell(25,5, $pdf->Image($pic,10,5,60),0,0);
	  
	   $pdf-> SetFont("Arial","",12);
    $pdf->Cell(8);
    $pdf->SetX($pdf->GetX() - 210 );
    $pdf-> SetFont("Arial","BU",13);
    $pdf->Cell(25,5,'Purchase Request',0,1);         
    $pdf->ln(3);

	  
    $pdf->SetFont('Arial','BU',11);
    $pdf->SetX($pdf->GetX() - 95 );
    $pdf->Cell(40,7,'Generated By:',0,0,'C');
    $pdf->SetFont('Arial','',11);
    $pdf->SetX($pdf->GetX() - 5 );
    $pdf->Cell(26,7,$id1,0,1,'C');

    $pdf->SetFont('Arial','BU',11);
    $pdf->SetX($pdf->GetX() - 100 );
    $pdf->Cell(40,7,'Sys Date:',0,0,'C');
    $pdf->SetFont('Arial','',11);

    $pdf->Cell(26,7,$time,0,1,'C');
	
	
    
	$pdf->ln(7);
 $pdf->Cell(2);
$pdf->Code128(217, $pdf->GetY() -6,$barcode3,50,10);
 $pdf->SetFont('Arial','BU',11);  
    $pdf->SetX($pdf->GetX() -300 );
    $pdf->Cell(40,7,'Branch Name:',0,0,'L');
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(60,7,ucfirst($branch_name),0,0,'L');
	
	 $pdf->SetFont('Arial','BU',11);  
    
    $pdf->Cell(40,7,'Request Date:',0,0,'L');
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(40,7,ucfirst($req_date),0,1,'L');
 $pdf->Cell(2);
	 $pdf->SetFont('Arial','BU',11);  
    $pdf->SetX($pdf->GetX() -300 );
    $pdf->Cell(40,7,'Request From:',0,0,'L');
    $pdf->SetFont('Arial','',10);

    $pdf->Cell(60,7,ucfirst($request_from),0,0,'L');


$pdf->SetFont('Arial','BU',11);  
    $pdf->Cell(40,7,'Remarks:',0,0,'L');
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(40,7,$remarks,0,1,'L');
 $pdf->ln(15);
    

    $pdf-> SetFont("Arial","BU",10);
//	$pdf->Cell(30);
     $pdf->Cell(12,7,'S.No',1,0,'C');
    $pdf->Cell(45,7,'Item',1,0,'C');
    $pdf->Cell(40,7,'UOM',1,0,'C');
	$pdf->Cell(30,7,'Rate',1,0,'C');
    $pdf->Cell(30,7,'Quantity',1,0,'C');
	    $pdf->Cell(30,7,'Discount',1,0,'C');
	$pdf->Cell(30,7,'Amount',1,0,'C');
	$pdf->Cell(60,7,'Remarks',1,1,'C');
	
$i=1;
$p=1;    
  
$r = mysqli_query($conn, "select * from purchase_request_detail a , item_setup2 b where a.req_id = '$request_id' and a.item_code = b.item_id "); 
  
	while (($rows = mysqli_fetch_array($r)) != false) {
	
	$req_id = $rows['REQ_ID'];
	$uom = $rows['UOM'];
	$quantity = $rows['QUANTITY'];
    $item_name = $rows['ITEM_NAME'];   
    $rate = $rows['RATE'];
	$discount = $rows['DISCOUNT'];
	$total_amount = $rate * $quantity - $discount;
	$remarks = $rows['REMARKS'];

$real_amount += $total_amount;
	
             $pdf->SetFont('Arial','',10);
//$pdf->Cell(30);			 
              $pdf->Cell(12,8,$i,1,0,'C');             
              $pdf->Cell(45,8,$item_name,1,0,'C');           
              $pdf->Cell(40,8,$uom,1,0,'C');     
			$pdf->Cell(30,8,number_format($rate),1,0,'C');
              $pdf->Cell(30,8,number_format($quantity),1,0,'C');
$pdf->Cell(30,8,number_format($discount),1,0,'C');
$pdf->Cell(30,8,number_format($total_amount),1,0,'C');
$pdf->MultiCell(60,8,$remarks,1,1);
            
$i++;


}

             $pdf->SetFont('Arial','B',11);

              $pdf->Cell(57,8,'Total',1,0,'C');             
              $pdf->Cell(40,8,'',1,0,'C');     
			$pdf->Cell(30,8,'',1,0,'C');
              $pdf->Cell(30,8,'',1,0,'C');
$pdf->Cell(30,8,'',1,0,'C');
$pdf->Cell(30,8,number_format($real_amount),1,0,'C');
$pdf->MultiCell(60,8,'',1,1);
            

            $pdf->Output();
                

?>